name: Migrate

on:
  push:
    branches:
      - dev
    paths:
      - 'apps/api/prisma/**'
  workflow_dispatch: 

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Generate Prisma Client
        run: npx prisma generate --schema=apps/api/prisma/schema.prisma

      - name: Run migration
        run: npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma
        env:
          # We map the Direct URL to the standard DATABASE_URL name
          # so the prisma.config.ts can find it easily.
          DATABASE_URL: ${{ secrets.DIRECT_URL }}
          PRISMA_CONFIG_PATH: apps/api/prisma/prisma.config.ts